spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qingxu
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

qingxu:
  security:
    csrf:
      enabled: true

logging:
  level:
    com.qingxu.qingxuapi: warn
